services:
  evolution-api:
    image: evolutionapi/evolution-api:latest # <--- ESTA ES LA CORRECTA
    container_name: evolution_api
    restart: always
    ports:
      - "9090:9090"
    env_file:
      - .env
    volumes:
      - evolution_data:/evolution/instances
    networks:
      - evolution_net

volumes:
  evolution_data:

networks:
  evolution_net:
    driver: bridge
